name: Tumblr-Bluesky-Crossposter

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run-crossposter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg imagemagick libmagic1

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests atproto python-magic pillow

      - name: Run the crossposter
        env:
          TUMBLR_API_KEY: ${{ secrets.TUMBLR_API_KEY }}
          TUMBLR_BLOG_IDENTIFIER: ${{ secrets.TUMBLR_BLOG_IDENTIFIER }}
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python tumsky_cross.py
